name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: code builds successfully
      id: code-builds-successfully
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: code builds successfully
        setup-command: ''
        command: make
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CODE-BUILDS-SUCCESSFULLY_RESULTS: "${{steps.code-builds-successfully.outputs.result}}"
      with:
        runners: code-builds-successfully
